### ISSUE TITLE
Remove lcms optional dependancy

### ISSUE THREAD

**Issue by aforsythe** [miaoqi/rawtoACES#2]
We don't need it for this utility

**Comment by miaoqi** [comment]
I have done this by largely cleaning up configure file.

Thanks,


[Δ]<http://www.oscars.org>


Miaoqi Zhu
Lab Systems Administrator


Academy of Motion Picture Arts and Sciences
Science & Technology Council
1313 Vine Street • Hollywood, CA 90028


310.247.3000 x3302 • MZhu@oscars.org<mailto:MZhu@oscars.org>

**Comment by aforsythe** [comment]
Thanks @miaoqi , 

I can see you addressed it in caa0c987979901dbf9fa4c7a509023cc1f09be74 after I created the issue.

When you make a commit to address an issue you can add a line in the commit message to automatically close the issue by writing "closes" and the number of the issue.  For example in this case you could have written :  closes #2
